# Form implementation generated from reading ui file 'ui_files/ip_info.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class IpInfoWindowDesign(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(945, 518)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 951, 521))
        self.frame.setStyleSheet("background-color: rgb(163, 163, 163);\n"
"color: black;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.title = QtWidgets.QLabel(parent=self.frame)
        self.title.setStyleSheet("color: white;\n"
"font-size: 50px;\n"
"font-weight: 800;")
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 0, 0, 1, 1)
        self.info = QtWidgets.QLabel(parent=self.frame)
        self.info.setStyleSheet("color: white;\n"
"font-size: 20px;")
        self.info.setText("")
        self.info.setObjectName("info")
        self.gridLayout.addWidget(self.info, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.frame)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ip-Hack"))
        self.title.setText(_translate("MainWindow", "Info for"))
