# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class MainWindowDesign(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 313)
        self.frame = QtWidgets.QFrame(parent=MainWindow)
        self.frame.setGeometry(QtCore.QRect(0, 0, 901, 321))
        self.frame.setStyleSheet("background-color: rgb(163, 163, 163);\n"
"color: black;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setStyleSheet("color: white;\n"
"font-size: 50px;\n"
"font-weight: 800;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.ip = QtWidgets.QLineEdit(parent=self.frame)
        self.ip.setStyleSheet("background-color: rgb(246, 246, 246);\n"
"border-radius: 20px;\n"
"padding-left: 5px;")
        self.ip.setFixedHeight(50)
        self.ip.setObjectName("ip")
        self.gridLayout.addWidget(self.ip, 1, 0, 1, 1)
        self.get_info = QtWidgets.QPushButton(parent=self.frame)
        self.get_info.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.get_info.setStyleSheet("QPushButton {\n"
"    background-color: rgb(133, 133, 133);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(138, 138, 138);\n"
"}")
        self.get_info.setObjectName("get_info")
        self.get_info.setFixedHeight(50)
        self.gridLayout.addWidget(self.get_info, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.frame)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IP-Hack"))
        self.label.setText(_translate("MainWindow", "IP-Hack"))
        self.ip.setPlaceholderText(_translate("MainWindow", "IP"))
        self.get_info.setText(_translate("MainWindow", "Get info about IP"))
